### PR TITLE
Add sample data for single item

### PR DESCRIPTION
**Pull request by lancerutkin**
@tomcernera @kevypark @Qwill take a look at this sample data - is this everything we all need?

### CODE REVIEW

**Comment by tomcernera** [comment]
Product 1 info looks good.

**Comment by Qwill** [comment]
We also need review metadata GET /reviews/:product_id/meta

**Comment by lancerutkin** [comment]
Thanks, added the metadata

**Comment by Qwill** [comment]
Since the data is all stringified, should we be consistent and encase the object names in quotes as well?

**Comment by lancerutkin** [comment]
No need - we can access the information directly as properties of the object - JS is smart enough to know what we mean.

**Comment by Qwill** [comment]
Then it looks good on my end.

**Pull request merged**
