### PR TITLE
add .travis.yml file

### PR DESCRIPTION
**Pull request by Qwill**
@lancerutkin @kevypark @tomcernera Added the travis configuration file, please take a look.

### CODE REVIEW

**Comment by lancerutkin** [comment]
Take a look at coverage scripts before we merge this

**Comment by tomcernera** [comment]
package.json test: jest --coverage

**Comment by lancerutkin** [comment]
Can you confirm that this is the appropriate way of doing this? I.e., every
time we test, we want to test for coverage? Or do we want a special script
for that?

**Comment by tomcernera** [comment]
Per our conversation let's hold off on --coverage until we can quantify the time difference.

**Pull request merged**
