### PR TITLE
add server file

### PR DESCRIPTION
**Pull request by Qwill**

### CODE REVIEW

**Comment by lancerutkin** [comment]
@Qwill I'll take a look at this

**Comment by lancerutkin** [comment]
@Qwill let's check for a process.env.PORT before assigning the hardcoded value. That will make it easier when we need to deploy.

**Comment by Qwill** [comment]
I added the check.

**Comment by lancerutkin** [comment]
I am unsure whether or not PORT is a keyword/case sensitive. I've only ever seen it as process.env.PORT though. Let's change it to that to be safe.

**Comment by Qwill** [comment]
PORT is now uppercase.

**Comment by lancerutkin** [comment]
Looks good.

**Pull request merged**
