### PR TITLE
Webpack init

### PR DESCRIPTION
**Pull request by lancerutkin**
@tomcernera @kevypark @Qwill can you guys take a look at this and see if it looks good? I used createapp.dev to build out webpack.

### CODE REVIEW

**Comment by Qwill** [comment]
Add the "externals" config object to webpack.config.js so that redux is handled properly.

**Comment by Qwill** [comment]
The gitignore file should also ignore dist/bundle.js

**Comment by lancerutkin** [comment]
@Qwill I added the externals object. Let's hold off on adding the bundle to gitignore since we don't actually have that file yet. Let's make a practice of adding files like that, as well as .env, as we add them, and not before. Ultimately, our bundle may not be in a folder called "dist".

**Comment by Qwill** [comment]
Looks good

**Pull request merged**
